"""add composite index on health records

Revision ID: 03f2a79b1f62
Revises: fec2b4f4e03d
Create Date: 2026-09-19 15:05:36.939487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '03f2a79b1f62'
down_revision: Union[str, None] = 'fec2b4f4e03d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_health_records_patient_recorded', 'health_records', ['patient_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_health_records_patient_recorded', table_name='health_records')
    # ### end Alembic commands ###